/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.text.DateFormat;
import DAO.AdministradorDAO;
import DAO.LocatarioDAO;
import DAO.VeiculoDAO;
import Model.Administrador;
import Model.Locacao;
import Model.Locatario;
import Model.Veiculo;
import java.text.SimpleDateFormat;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Month;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Pedro Maschio
 */
public class F_DadosLocacao extends javax.swing.JFrame {
    static int idAdmin;
    static int idVeiculo;
    static int idLocatario;
    
    public void mascaraCampos(){
        try {
            MaskFormatter mascaraData = new MaskFormatter("##/##/####");
            //mascaraData.install(f_dataDevolucao);
        }catch(Exception ex){
            throw new RuntimeException(ex);
        }
    }
    /**
     * Creates new form F_DadosLocacao
     */
    public F_DadosLocacao(int idAdmin, int idVeiculo, int idLocatario) {
       
        initComponents();
        mascaraCampos();
        SpinnerNumberModel a = new SpinnerNumberModel();
        a.setMinimum(1);
        a.setMaximum(30);
        a.setValue(1);
        spinner_dias.setModel(a);
        this.idAdmin = idAdmin;
        this.idVeiculo = idVeiculo;
        this.idLocatario = idLocatario;
         this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        f_marca = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        f_modelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        f_placa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        f_email = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        f_capacidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        f_quantComb = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        f_numeroLocatario = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        f_horarioSaida = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        f_cor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        f_cnpj = new javax.swing.JTextField();
        f_endereco = new javax.swing.JLabel();
        f_bairro = new javax.swing.JTextField();
        f_cpf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        f_enderecoLocatario = new javax.swing.JTextField();
        f_dataSaida = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        f_enderecoLocadora = new javax.swing.JTextField();
        f_cidade = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        f_lancamento = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        f_dataNascimento = new javax.swing.JTextField();
        f_cnh = new javax.swing.JTextField();
        f_telefoneLocatario = new javax.swing.JTextField();
        f_nomeLocadora = new javax.swing.JTextField();
        f_endereco1 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        f_emailLocatario = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        f_nomeLocatario = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        f_tipoComb = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        spinner_dias = new javax.swing.JSpinner();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        f_dataDevolucao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dados da Locação");
        setPreferredSize(new java.awt.Dimension(1200, 700));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Marca:");

        f_marca.setEditable(false);
        f_marca.setFocusable(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Cidade:");

        f_modelo.setEditable(false);
        f_modelo.setFocusable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("CNPJ:");

        f_placa.setEditable(false);
        f_placa.setFocusable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("E-mail:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Tipo de Combustível:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nome:");

        f_email.setEditable(false);
        f_email.setFocusable(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("E-mail:");

        f_capacidade.setEditable(false);
        f_capacidade.setFocusable(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Nome:");

        f_quantComb.setEditable(false);
        f_quantComb.setFocusable(false);
        f_quantComb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_quantCombActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel27.setText("Período de Locação:");

        jLabel24.setText("Dados da Locação");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Telefone:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Endereço:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("CPF:");

        f_numeroLocatario.setEditable(false);
        f_numeroLocatario.setFocusable(false);
        f_numeroLocatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_numeroLocatarioActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Horário de Saída:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("CNH:");

        jLabel7.setText("Dados do Locatário");

        f_horarioSaida.setEditable(false);
        f_horarioSaida.setFocusable(false);
        f_horarioSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_horarioSaidaActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));

        f_cor.setEditable(false);
        f_cor.setFocusable(false);

        jButton1.setBackground(new java.awt.Color(21, 190, 4));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("CONFIRMAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        f_cnpj.setEditable(false);
        f_cnpj.setFocusable(false);

        f_endereco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        f_endereco.setText("Endereço:");

        f_bairro.setEditable(false);
        f_bairro.setFocusable(false);

        f_cpf.setEditable(false);
        f_cpf.setFocusable(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Data de nascimento:");

        f_enderecoLocatario.setEditable(false);
        f_enderecoLocatario.setFocusable(false);

        f_dataSaida.setEditable(false);
        f_dataSaida.setFocusable(false);
        f_dataSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_dataSaidaActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Cor:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Lançamento:");

        f_enderecoLocadora.setEditable(false);
        f_enderecoLocadora.setFocusable(false);

        f_cidade.setEditable(false);
        f_cidade.setFocusable(false);

        f_lancamento.setEditable(false);
        f_lancamento.setFocusable(false);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("litros");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Data de Saída:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Quantidade de Combustível:");

        f_dataNascimento.setEditable(false);
        f_dataNascimento.setFocusable(false);

        f_cnh.setEditable(false);
        f_cnh.setFocusable(false);

        f_telefoneLocatario.setEditable(false);
        f_telefoneLocatario.setFocusable(false);

        f_nomeLocadora.setEditable(false);
        f_nomeLocadora.setFocusable(false);

        f_endereco1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        f_endereco1.setText("Número:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Placa:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Bairro:");

        f_emailLocatario.setEditable(false);
        f_emailLocatario.setFocusable(false);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Capacidade do Tanque:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Modelo:");

        jLabel15.setText("Dados do Veículo");

        f_nomeLocatario.setEditable(false);
        f_nomeLocatario.setFocusable(false);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("litros");

        f_tipoComb.setEditable(false);
        f_tipoComb.setFocusable(false);

        jLabel2.setText("Dados da locadora");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Dados da Locação");

        spinner_dias.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner_diasStateChanged(evt);
            }
        });

        jLabel31.setText("dias");

        jLabel32.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel32.setText("Data de Devolução:");

        f_dataDevolucao.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel22))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(f_modelo, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                            .addComponent(f_marca)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(f_capacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel28)))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel23))
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(f_cor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(f_tipoComb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(f_quantComb)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel18)
                                                .addGap(8, 8, 8)))
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel29)
                                                .addGap(64, 64, 64))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(f_lancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(f_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel9))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(f_dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(f_nomeLocatario, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                            .addComponent(f_cidade)
                                            .addComponent(f_bairro))
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(f_endereco)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(f_enderecoLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(43, 43, 43)
                                                .addComponent(f_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(f_endereco1)
                                                .addGap(18, 18, 18)
                                                .addComponent(f_numeroLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(f_cnh, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel30))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(f_emailLocatario, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                                            .addComponent(f_telefoneLocatario)))
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5))
                                        .addGap(98, 98, 98)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(f_nomeLocadora, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                            .addComponent(f_enderecoLocadora))
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(f_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(f_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(629, 629, 629)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel24))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(f_horarioSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(173, 173, 173)
                                        .addComponent(f_dataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(173, 173, 173)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel32))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spinner_dias, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel31))
                            .addComponent(f_dataDevolucao))
                        .addGap(607, 607, 607))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(648, 648, 648)
                        .addComponent(jButton1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f_cnpj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(f_nomeLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(f_enderecoLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(f_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(f_nomeLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_endereco)
                    .addComponent(f_enderecoLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(f_emailLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(f_numeroLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_endereco1)
                    .addComponent(jLabel30)
                    .addComponent(f_telefoneLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(f_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(f_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(f_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(f_cnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(f_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel19)
                            .addComponent(f_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(f_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21))
                                .addComponent(jLabel17))
                            .addComponent(f_tipoComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(f_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(f_lancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_capacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel28)
                    .addComponent(jLabel23)
                    .addComponent(f_quantComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(f_dataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(spinner_dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(f_horarioSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(f_dataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(196, 196, 196))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f_numeroLocatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_numeroLocatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_numeroLocatarioActionPerformed

    private void f_horarioSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_horarioSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_horarioSaidaActionPerformed



    /*public boolean isValidDate(String date){
        boolean retorno = false;
    try {
            GregorianCalendar gc = new GregorianCalendar();
            gc.setLenient(false);        // must do this
            String datas[] = date.split("/", 3);
            String ano = datas[0];
         
            String mes = datas[1];
      
            String dia = datas[2];
     
            gc.set(GregorianCalendar.YEAR, Integer.parseInt(ano));
            gc.set(GregorianCalendar.MONTH, (Integer.parseInt(mes)));// invalid month
            gc.set(GregorianCalendar.DATE, Integer.parseInt(dia));

            gc.getTime(); // exception thrown here
            
            retorno = true;
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    return retorno;
    }*/
    public boolean validar(){
        Calendar c1 = Calendar.getInstance();
        Calendar c2 = Calendar.getInstance(); 
        
        Date date1 = new Date();
        
        
        DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        try {
            c1.setTime(formatter.parse(f_dataSaida.getText()));
            
        } catch(Exception ex){
            throw new RuntimeException();
        }
      
        try {
            c2.setTime(formatter.parse(f_dataDevolucao.getText()));
            
        } catch(Exception ex){
            throw new RuntimeException();
        }        
        long saida = c1.getTimeInMillis();
        long devolucao = c2.getTimeInMillis();
        if(devolucao > saida){
            return true;            
        } else {
            return false;
        }
        
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    //if(isValidDate(f_dataDevolucao.getText().trim())){    
        if(validar()){
            dispose();
            Locacao l = new Locacao();
            l.setCapaciTanque(Double.parseDouble(f_capacidade.getText()));
            l.setCnhLocatario(f_cnh.getText());
            l.setCnpjLocadora(f_cnpj.getText());
            l.setCor(f_cor.getText());
            l.setCpfLocatario(f_cpf.getText());
            l.setDataDevolucao(f_dataDevolucao.getText());
            l.setDataSaida(f_dataSaida.getText());
            l.setEmailLocadora(f_email.getText());
            l.setEmailLocatario(f_emailLocatario.getText());
            l.setEnderecoLocadora(f_enderecoLocadora.getText());
            l.setEnderecoLocatario(f_cidade.getText());
            l.setHorarioSaida(f_horarioSaida.getText());
            l.setMarca(f_marca.getText());
            l.setModelo(f_modelo.getText());
            l.setNascLocatario(f_dataNascimento.getText());
            l.setNomeLocadora(f_nomeLocadora.getText());
            l.setNomeLocatario(f_nomeLocatario.getText());
            l.setQuantTanque(Double.parseDouble(f_quantComb.getText()));
            l.setTelefoneLocatario(f_telefoneLocatario.getText());
            l.setTipoComb(f_tipoComb.getText());
            l.setAnoLancamento(f_lancamento.getText());
            l.setCidadeLocatario(f_cidade.getText());
            l.setBairroLocatario(f_bairro.getText());
            l.setNumeroLocatario(f_numeroLocatario.getText());
            l.setPlaca(f_placa.getText());
            F_Contrato contrato = new F_Contrato(l, idAdmin, idVeiculo);
            contrato.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "A data de devolução deve ser posterior a data de aquisição!");
        }
      //  } else {
        //    JOptionPane.showMessageDialog(null, "Informe uma data válida!");
        //} 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void f_dataSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_dataSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_dataSaidaActionPerformed

    private void f_quantCombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_quantCombActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_quantCombActionPerformed

    private void spinner_diasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner_diasStateChanged
        Calendar c = Calendar.getInstance();
        DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        String saida = f_dataSaida.getText();
        c.set(Integer.parseInt(saida.substring(6, 10)), Integer.parseInt(saida.substring(3, 5)), Integer.parseInt(saida.substring(0, 2)));
        int diaint = Integer.parseInt(saida.substring(6, 10));
        int mesint = Integer.parseInt(saida.substring(3, 5));
        int anoint = Integer.parseInt(saida.substring(0, 2));
        
        int dias = Integer.parseInt(spinner_dias.getValue().toString());
        LocalDate date = LocalDate.of(diaint, mesint, anoint).plusDays(dias);
        
        
        String dia = String.valueOf(date.getDayOfMonth());
        String mes = String.valueOf(date.getMonthValue());
        String ano = String.valueOf(date.getYear());
        String data = dia + "/" +  mes + "/" + ano;

        
        f_dataDevolucao.setText(data);
        // TODO add your handling code here:
    }//GEN-LAST:event_spinner_diasStateChanged
    public void preencheLocacao(int idLocatario, int idVeiculo, int idAdmin){
        // Administrador
        Administrador a = new Administrador();
        AdministradorDAO administradorDAO = new AdministradorDAO();
        a = administradorDAO.buscar(idAdmin);
        f_nomeLocadora.setText(a.getNomeCompanhia());
        f_enderecoLocadora.setText(a.getEnderecoCompanhia());
        f_cnpj.setText(a.getCNPJ());
        f_email.setText(a.getEmail());
        
        // Locatário
        Locatario l = new Locatario();
        LocatarioDAO locatarioDAO = new LocatarioDAO();
        
        l = locatarioDAO.buscar(idLocatario, idAdmin);
        
        f_nomeLocatario.setText(l.getNomeCompleto());
        f_dataNascimento.setText(l.getNascimento());
        f_cidade.setText(l.getCidade());
        f_telefoneLocatario.setText(l.getTelefone());
        f_cnh.setText(l.getCnh());
        f_cpf.setText(l.getCpf());
        f_bairro.setText(l.getBairro());
        f_enderecoLocatario.setText(l.getEndereco());
        f_numeroLocatario.setText(l.getNumero());
        f_emailLocatario.setText(l.getEmail());
        
        // Veículo
        Veiculo v = new Veiculo();
        VeiculoDAO veiculoDAO = new VeiculoDAO();
        v = veiculoDAO.buscar(idVeiculo);
        
        f_marca.setText(v.getMarca());
        f_modelo.setText(v.getModelo());
        f_capacidade.setText(Double.toString(v.getCapacidadeTanque()));
        f_cor.setText(v.getCor());
        f_tipoComb.setText(v.getTipoComb());
        f_quantComb.setText(Double.toString(v.getQuantComb()));
        f_placa.setText(v.getPlaca());
        f_lancamento.setText(String.valueOf(v.getAnoLancamento()));
        
        // Locação
        Date hoje = new Date();
        SimpleDateFormat df;
        df = new SimpleDateFormat("dd/MM/yyyy");
        
        f_dataSaida.setText(df.format(hoje));
        
        Calendar calendar = new GregorianCalendar();
	Date trialTime = new Date();
	calendar.setTime(trialTime);
	String hora = String.valueOf(calendar.get(Calendar.HOUR_OF_DAY));
	String minutos = String.valueOf(calendar.get(Calendar.MINUTE));
	String segundos = String.valueOf(calendar.get(Calendar.SECOND));
        
        f_horarioSaida.setText(hora + " : " + minutos + " : " + segundos);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_DadosLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_DadosLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_DadosLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_DadosLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_DadosLocacao(idAdmin, idVeiculo, idLocatario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField f_bairro;
    private javax.swing.JTextField f_capacidade;
    private javax.swing.JTextField f_cidade;
    private javax.swing.JTextField f_cnh;
    private javax.swing.JTextField f_cnpj;
    private javax.swing.JTextField f_cor;
    private javax.swing.JTextField f_cpf;
    private javax.swing.JTextField f_dataDevolucao;
    private javax.swing.JTextField f_dataNascimento;
    private javax.swing.JTextField f_dataSaida;
    private javax.swing.JTextField f_email;
    private javax.swing.JTextField f_emailLocatario;
    private javax.swing.JLabel f_endereco;
    private javax.swing.JLabel f_endereco1;
    private javax.swing.JTextField f_enderecoLocadora;
    private javax.swing.JTextField f_enderecoLocatario;
    private javax.swing.JTextField f_horarioSaida;
    private javax.swing.JTextField f_lancamento;
    private javax.swing.JTextField f_marca;
    private javax.swing.JTextField f_modelo;
    private javax.swing.JTextField f_nomeLocadora;
    private javax.swing.JTextField f_nomeLocatario;
    private javax.swing.JTextField f_numeroLocatario;
    private javax.swing.JTextField f_placa;
    private javax.swing.JTextField f_quantComb;
    private javax.swing.JTextField f_telefoneLocatario;
    private javax.swing.JTextField f_tipoComb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSpinner spinner_dias;
    // End of variables declaration//GEN-END:variables
}
