/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.VeiculoDAO;
import Model.Veiculo;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Pedro Maschio
 */
public class F_EditarVeiculo extends javax.swing.JFrame {
    static int id;
    MaskFormatter mascaraPlaca, mascaraAnoLancamento, mascaraQuantCombustivel;
    MaskFormatter mascaraAnoAquisicao, mascaraCapaciTanque;
    VeiculoDAO veiculoDAO;
    public void defineMascaras(){
        try {
            mascaraPlaca = new MaskFormatter("UUU-####");
            mascaraAnoLancamento = new MaskFormatter("####");
            mascaraQuantCombustivel = new MaskFormatter("###");
            mascaraAnoAquisicao = new MaskFormatter("####");
            mascaraCapaciTanque = new MaskFormatter("###");
            mascaraPlaca.install(f_placa);
            mascaraAnoLancamento.install(f_anoLancamento);
            mascaraAnoAquisicao.install(f_anoAquisicao);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Ocorreu um erro!");
            throw new RuntimeException(ex);
        }
    }
    /**
     * Creates new form F_EditarVeiculo
     */
    public F_EditarVeiculo(int id) {
        veiculoDAO = new VeiculoDAO();
        initComponents();
        defineMascaras();
        this.id = id;
                SpinnerNumberModel a = new SpinnerNumberModel();
        a.setMinimum(0);
        f_capaci.setModel(a);
        SpinnerNumberModel b = new SpinnerNumberModel();
        b.setMinimum(0);
        f_quant.setModel(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        f_marca = new javax.swing.JTextField();
        f_modelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        f_cor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Combo_TipoComb = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CheckBox_Cadeirinha = new javax.swing.JCheckBox();
        CheckBox_GPS = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        f_observacao = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        f_placa = new javax.swing.JFormattedTextField(mascaraPlaca);
        f_anoLancamento = new javax.swing.JFormattedTextField(mascaraAnoLancamento);
        f_anoAquisicao = new javax.swing.JFormattedTextField(mascaraAnoAquisicao);
        jLabel15 = new javax.swing.JLabel();
        f_capaci = new javax.swing.JSpinner();
        f_quant = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Marca:");

        f_marca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        f_marca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                f_marcaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                f_marcaFocusLost(evt);
            }
        });

        f_modelo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        f_modelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                f_modeloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                f_modeloFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Modelo:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Placa:");

        f_cor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        f_cor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                f_corFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                f_corFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Cor:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Ano Lançamento:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Ano de Aquisição:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Tipo de Combustível:");

        Combo_TipoComb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Combo_TipoComb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasolina", "Álcool", "Flex" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Quantidade de Combustível:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Litros");

        CheckBox_Cadeirinha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBox_Cadeirinha.setText("Cadeirinha ");
        CheckBox_Cadeirinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_CadeirinhaActionPerformed(evt);
            }
        });

        CheckBox_GPS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CheckBox_GPS.setText("GPS");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Acessórios:");

        f_observacao.setColumns(20);
        f_observacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        f_observacao.setRows(5);
        jScrollPane1.setViewportView(f_observacao);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Observações:");

        jButton1.setBackground(new java.awt.Color(21, 190, 4));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("SALVAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Editar Veículo");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Capacidade do tanque:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Litros");

        f_placa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        f_placa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                f_placaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                f_placaFocusLost(evt);
            }
        });

        f_anoLancamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        f_anoLancamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                f_anoLancamentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                f_anoLancamentoFocusLost(evt);
            }
        });

        f_anoAquisicao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        f_anoAquisicao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                f_anoAquisicaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                f_anoAquisicaoFocusLost(evt);
            }
        });

        jLabel15.setText("Opcional");

        f_capaci.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        f_capaci.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                f_capaciFocusLost(evt);
            }
        });

        f_quant.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(335, 335, 335))
            .addGroup(layout.createSequentialGroup()
                .addGap(403, 403, 403)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Combo_TipoComb, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(238, 238, 238)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(f_capaci)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addGap(23, 23, 23))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CheckBox_GPS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CheckBox_Cadeirinha, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(f_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(f_anoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(f_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(f_quant, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(117, 117, 117)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(f_cor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f_anoAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(64, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(f_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(f_anoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f_anoAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Combo_TipoComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(f_capaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(CheckBox_GPS)
                    .addComponent(CheckBox_Cadeirinha)
                    .addComponent(f_quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(70, 70, 70)
                .addComponent(jButton1)
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBox_CadeirinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_CadeirinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBox_CadeirinhaActionPerformed
    public boolean validar(){
        String marca = f_marca.getText().trim();
        String modelo = f_modelo.getText().trim();
        String placa = f_placa.getText();
        String quant = f_quant.getValue().toString().trim();
        String capaci = f_capaci.getValue().toString().trim();

        if(marca.equals("") || modelo.equals("") || placa.equals("") || quant.equals("") || capaci.equals("")) {
            return false;
        }
        else 
            return true;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(validar()){
                if(Integer.parseInt(f_anoLancamento.getText().trim()) <= Integer.parseInt(f_anoAquisicao.getText().trim())){
                    if(Integer.parseInt((f_quant.getValue().toString())) <= (Integer.parseInt(f_capaci.getValue().toString()))){
                        VeiculoDAO veiculoDAO = new VeiculoDAO();
                        Veiculo v = new Veiculo();
        
                        v.setId(id);
                        v.setMarca(f_marca.getText());
                        v.setModelo(f_modelo.getText());
                        v.setPlaca(f_placa.getText());
                        v.setCor(f_cor.getText());
                        v.setAnoLancamento(Integer.parseInt(f_anoLancamento.getText().trim()));
                        v.setAnoAquisicao(Integer.parseInt(f_anoAquisicao.getText().trim()));
                        v.setCapacidadeTanque(Integer.parseInt(f_capaci.getValue().toString()));
        
                        int tipoComb = Combo_TipoComb.getSelectedIndex();
                        if(tipoComb == 0)
                            v.setTipoComb("Gasolina");
                        else if(tipoComb == 1)
                            v.setTipoComb("Álcool");
                        else if(tipoComb == 2)
                            v.setTipoComb("Flex");

                        v.setQuantComb(Integer.parseInt(f_quant.getValue().toString()));
                        if(CheckBox_GPS.isSelected() && CheckBox_Cadeirinha.isSelected()){
                            v.setAcessorios("GPS e Cadeirinha para Bebê");
                        } else if(CheckBox_GPS.isSelected()){
                            v.setAcessorios("GPS");
                        } else if(CheckBox_Cadeirinha.isSelected()){
                            v.setAcessorios("Cadeirinha para Bebê");
                        } else {
                            v.setAcessorios("Nenhum acessório no veículo");
                        }
        
                        v.setObservacao(f_observacao.getText());
                        veiculoDAO.editar(v);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null,"O ano de lançamento é inferior ao ano de aquisição");
                    }
                    } else {
                        JOptionPane.showMessageDialog(null, "A quantidade de combustível no tanque é superior a sua capacidade");
                    }
                    
                } else {
                JOptionPane.showMessageDialog(null, "Há campos não preenchidos!");           
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void f_marcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_marcaFocusLost
        // TODO add your handling code here:
        if(f_marca.getText().equals("")){
            f_marca.setBackground(java.awt.Color.getHSBColor(0, 79, 66));
        }           
    }//GEN-LAST:event_f_marcaFocusLost

    private void f_modeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_modeloFocusLost
        if(f_modelo.getText().equals("")){
            f_modelo.setBackground(java.awt.Color.getHSBColor(0, 79, 66));
        }           // TODO add your handling code here:
    }//GEN-LAST:event_f_modeloFocusLost

    private void f_placaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_placaFocusLost
        if(f_placa.getText().equals("   -    ")){
            f_placa.setBackground(java.awt.Color.getHSBColor(0, 79, 66));
        }          // TODO add your handling code here:
    }//GEN-LAST:event_f_placaFocusLost

    private void f_corFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_corFocusLost
        if(f_cor.getText().equals("")){
            f_cor.setBackground(java.awt.Color.getHSBColor(0, 79, 66));
        }         // TODO add your handling code here:
    }//GEN-LAST:event_f_corFocusLost

    private void f_anoLancamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_anoLancamentoFocusLost
        if(f_anoLancamento.getText().trim().equals("")){
            f_anoLancamento.setBackground(java.awt.Color.getHSBColor(0, 79, 66));
        }         // TODO add your handling code here:
    }//GEN-LAST:event_f_anoLancamentoFocusLost

    private void f_anoAquisicaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_anoAquisicaoFocusLost
        if(f_anoAquisicao.getText().trim().equals("")){
            f_anoAquisicao.setBackground(java.awt.Color.getHSBColor(0, 79, 66));
        }    // TODO add your handling code here:
    }//GEN-LAST:event_f_anoAquisicaoFocusLost

    private void f_capaciFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_capaciFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_f_capaciFocusLost

    private void f_marcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_marcaFocusGained
        f_marca.setBackground(java.awt.Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_f_marcaFocusGained

    private void f_modeloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_modeloFocusGained
        f_modelo.setBackground(java.awt.Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_f_modeloFocusGained

    private void f_placaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_placaFocusGained
        f_placa.setBackground(java.awt.Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_f_placaFocusGained

    private void f_corFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_corFocusGained
        f_cor.setBackground(java.awt.Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_f_corFocusGained

    private void f_anoLancamentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_anoLancamentoFocusGained
        f_anoLancamento.setBackground(java.awt.Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_f_anoLancamentoFocusGained

    private void f_anoAquisicaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_f_anoAquisicaoFocusGained
        f_anoAquisicao.setBackground(java.awt.Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_f_anoAquisicaoFocusGained
    public void preencheCampos(int id){
        VeiculoDAO veiculoDAO = new VeiculoDAO();
        Veiculo v = new Veiculo();
        v = veiculoDAO.buscar(id);
        
        
        f_marca.setText(v.getMarca());
        f_modelo.setText(v.getModelo());
        f_placa.setText(v.getPlaca());
        f_cor.setText(v.getCor());
        f_anoLancamento.setText(String.valueOf(v.getAnoLancamento()));
        f_anoAquisicao.setText(String.valueOf(v.getAnoAquisicao()));
        f_capaci.setValue(v.getCapacidadeTanque());
        int tipoComb =  1;
        String comb;
        comb = v.getTipoComb();
        if(comb.equals("Gasolina")){
            tipoComb = 0;
        } else if(comb.equals("Álcool")){
            tipoComb = 1;
        } else if(comb.equals("Flex"))
            tipoComb = 2;
        
        Combo_TipoComb.setSelectedIndex(tipoComb);  

        f_quant.setValue(v.getQuantComb());
        String acessorios = v.getAcessorios();
        if(acessorios.equals("GPS e Cadeirinha para Bebê")){
            CheckBox_GPS.setSelected(true);
            CheckBox_Cadeirinha.setSelected(true);
        } else if(acessorios.equals("GPS")){
            CheckBox_GPS.setSelected(true);
        } else if(acessorios.equals("Cadeirinha para Bebê")){
            CheckBox_Cadeirinha.setSelected(true);
        } 
        
        f_observacao.setText(v.getObservacao());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_EditarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_EditarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_EditarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_EditarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_EditarVeiculo(id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox_Cadeirinha;
    private javax.swing.JCheckBox CheckBox_GPS;
    private javax.swing.JComboBox<String> Combo_TipoComb;
    private javax.swing.JFormattedTextField f_anoAquisicao;
    private javax.swing.JFormattedTextField f_anoLancamento;
    private javax.swing.JSpinner f_capaci;
    private javax.swing.JTextField f_cor;
    private javax.swing.JTextField f_marca;
    private javax.swing.JTextField f_modelo;
    private javax.swing.JTextArea f_observacao;
    private javax.swing.JFormattedTextField f_placa;
    private javax.swing.JSpinner f_quant;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
